export function clearRuntimeFault(room: Record<string, unknown>): void;
export function createRuntimeFault(room: Record<string, unknown>, details?: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createActionEffectStateRuntime(): Readonly<Record<string, unknown>>;
export function applyDynamicGameStateCode(room: Record<string, unknown>, code: string): Readonly<Record<string, unknown>>;
export function evaluateCodeExpression(expression: string, state: Record<string, unknown>): unknown;
export function parseCodeLiteral(value: string): unknown;
export function splitStatements(code: string): readonly string[];
export function answerOutputKey(action: Record<string, unknown>): string;
export function currentAnswerStateId(room: Record<string, unknown>): string;
export function deletePlayerAnswerRecord(room: Record<string, unknown>, playerId: string): void;
export function latestSessionAnswerOutput(room: Record<string, unknown>): unknown;
export function resolveSessionAnswerOutput(room: Record<string, unknown>, options?: Record<string, unknown>): unknown;
export function sessionAnswerOutput(room: Record<string, unknown>, stateId: string, actionId: string): unknown;
export function storeCurrentMomentAnswers(room: Record<string, unknown>, options?: Record<string, unknown>): boolean;
export function storePlayerAnswerRecord(room: Record<string, unknown>, playerId: string, record: unknown): boolean;
export function resetGameSessionState(room: Record<string, unknown>): void;
export function createPlayerPublicRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createPlayerStateRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createInputStateRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createPauseRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createCountdownRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createCraftingTimerRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createFlowNavigationRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createFlowTargetRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function flowStateHasActionType(state: unknown, type: string): boolean;
export function isCraftingStateId(stateId: unknown): boolean;
export function isRoundIntroStateId(stateId: unknown): boolean;
export function createDecisionRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createDecisionActionNormalizationRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createGameFlowMergeRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
