export function cleanChoiceOptions(value: unknown): string[];
export function cleanFlowText(value: unknown, fallback?: string): string;
export function cleanLayoutSelector(value: unknown): string;
export function cleanLayoutText(value: unknown): string;
export function cleanPlayerName(value: unknown): string;
export function cleanSubmittedText(value: unknown, limit?: number): string;
export function normalizeCharacterLimit(value: unknown): number;
export function normalizeChoiceInputMode(value: unknown): string;
export function normalizeColor(value: unknown): string;
export function normalizeConstantFloat(value: unknown, fallback: number, min?: number, max?: number): number;
export function normalizeConstantInteger(value: unknown, fallback: number, min?: number, max?: number): number;
export function normalizeConstantString(value: unknown, fallback: string, maxLength?: number): string;
export function normalizeDurationSeconds(value: unknown, fallback?: number): number;
export function normalizeFlowId(value: unknown, fallback: string): string;
export function normalizeFlowVariableName(value: unknown, fallback?: string): string;
export function normalizeLayoutNumber(value: unknown, fallback: number, min: number, max: number): number;
export function normalizePlayerFilter(value: unknown): string;
export function normalizePlayerId(value: unknown): string;
export function normalizeStageCode(value: unknown): string;
export function normalizeVotingCardFilter(value: unknown): string;
export function clearRuntimeFault(room: Record<string, unknown>): void;
export function createRuntimeFault(room: Record<string, unknown>, details?: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createActionEffectStateRuntime(): Readonly<Record<string, unknown>>;
export function applyDynamicGameStateCode(room: Record<string, unknown>, code: string): Readonly<Record<string, unknown>>;
export function evaluateCodeExpression(expression: string, state: Record<string, unknown>): unknown;
export function parseCodeLiteral(value: string): unknown;
export function splitStatements(code: string): readonly string[];
export function answerOutputKey(action: Record<string, unknown>): string;
export function currentAnswerStateId(room: Record<string, unknown>): string;
export function deletePlayerAnswerRecord(room: Record<string, unknown>, playerId: string): void;
export function latestSessionAnswerOutput(room: Record<string, unknown>): unknown;
export function resolveSessionAnswerOutput(room: Record<string, unknown>, options?: Record<string, unknown>): unknown;
export function sessionAnswerOutput(room: Record<string, unknown>, stateId: string, actionId: string): unknown;
export function storeCurrentMomentAnswers(room: Record<string, unknown>, options?: Record<string, unknown>): boolean;
export function storePlayerAnswerRecord(room: Record<string, unknown>, playerId: string, record: unknown): boolean;
export function resetGameSessionState(room: Record<string, unknown>): void;
export function createPlayerPublicRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createPlayerStateRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createInputStateRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createPauseRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createCountdownRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createCraftingTimerRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createFlowNavigationRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createFlowTargetRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function flowStateHasActionType(state: unknown, type: string): boolean;
export function isCraftingStateId(stateId: unknown): boolean;
export function isRoundIntroStateId(stateId: unknown): boolean;
export function createDecisionRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createDecisionActionNormalizationRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createGameFlowMergeRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function readAppVersion(rootDir: string): string;
export function readBuildNumber(rootDir: string): string;
export function contentTypeForFile(filePath: string): string;
export function readJson(request: Record<string, unknown>, maxBytes?: number): Promise<unknown>;
export function sendJson(response: Record<string, unknown>, status: number, payload: unknown): void;
export function createNetworkUrlsRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export * from "./web-service-runtime";
export function backupJsonFile(filePath: string, backupDirectory: string, prefix: string): void;
export function mirrorJsonFile(filePath: string, data: unknown): void;
export function readJsonFile(filePath: string): unknown;
export function writeJsonFile(filePath: string, data: unknown): void;
export function createRouterRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createStaticFilesRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createStageEventsRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createInactivePlayerSweepRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createPlayerAnswersRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createRoomBroadcastRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createDefaultRoom(stageCode: string): Record<string, unknown>;
export function createRoomStateRuntime(options?: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createVotingRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createRoomPhaseRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function resolveVotingAnswerSource(room: Record<string, unknown>, options?: Record<string, unknown>): unknown;
export function createMomentRouteRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createLobbyControlHandlersRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createStartHandlersRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createPlayerSessionHandlersRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createLobbyPayloadRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createHostAudioRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createTriviaContentRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export const TEXT_ANSWER_ACTION_CONFIGS: Readonly<Record<string, unknown>>;
export function isTextAnswerAction(actionOrType: unknown): boolean;
export function textAnswerActionConfig(actionOrType: unknown): Readonly<Record<string, unknown>> | null;
export function textAnswerPayloadTypeForMode(mode: unknown): string;
export function createControllerInputPayloadRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function controllerInputStaleError(payload: Record<string, unknown>, room: Record<string, unknown>, inputVisitId: number, label: string): string;
export function createControllerSubmitHandlersRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createActionCompletionRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createRoomActionEffectsRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createStageActionHandlersRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createFlowActionPublicRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createGameFlowNormalizationRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export * from "./game-readiness-runtime";
export * from "./game-service-runtime";
export * from "./content-game-data-runtime";
export function createRoomFlowHelpersRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createGameConstantsRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createLayoutNormalizationRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createStageLayoutNormalizationRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createControllerLayoutNormalizationRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createLayoutSyncRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createLocalDraftRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createToolDataReadRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createToolSourceReadersRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createToolSourceStoresRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function assertUniqueGameFlowIds(flow: unknown): void;
export function createToolPersistenceRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createGithubStorageRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createToolGithubSourcesRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createSaveHandlersRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
