export function createLayoutSyncRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createLocalDraftRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createToolDataReadRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createToolSourceStoresRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createGithubStorageRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createToolGithubSourcesRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function createSaveHandlersRuntime(options: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function compositionRevision(composition: unknown): string;
export function createArtCompositionDependencyReport(options?: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function normalizeArtOrganization(source?: Record<string, unknown>): Readonly<Record<string, unknown>>;
export function removeDeletedCompositionOrganizationKeys(organization: unknown, deletedIds: Iterable<string>): Readonly<Record<string, unknown>>;
